name: magallanes_cliente
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.24
  - pandas>=2.0
  - geopandas>=0.14
  - shapely>=2.0
  - rasterio>=1.3
  - scipy>=1.10
  - matplotlib>=3.7
  - networkx>=3.1
  - plotly>=5.20
  - folium>=0.16
  - pyproj>=3.5
  - pyshp>=2.3
  - openpyxl>=3.1
  - jupyter
  - ipykernel
  - pyyaml>=6.0
  - pip
  - pip:
      - arcgis>=2.3
